name: chatgpt-telegram-workers
services:
  chatgpt-telegram-workers:
    build: .
    ports:
      - "8787:8787"
    volumes:
      - ./config.json:/app/config.json:ro # change `./config.json` to your local path
      - ./wrangler.toml:/app/config.toml:ro # change `./wrangler.toml` to your local path
