# Change the name here to the name of your own workers.
name = 'chatgpt-telegram-workers'
workers_dev = true
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat_v2"]

# Deploy dist
main = './dist/index.js'   # Default use of dist/index.js

# Deploy Core version
# > pnpm run deploy:workers
#main = './packages/apps/workers/src/index.ts'
#main = './packages/apps/workers/dist/index.js'

# Deploy Vercel AI version
# > pnpm run deploy:workersnext
#main = './packages/apps/workers-next/src/index.ts'
#main = './packages/apps/workers-next/dist/index.js'

# Deploy Telegram MarkdownV2 version
# > pnpm run deploy:workersmk2
#main = './packages/apps/workers-mk2/src/index.ts'
#main = './packages/apps/workers-mk2/dist/index.js'


# The id here is a required field
# Please fill in your kv namespace id
# preview_id is only used for debugging, please delete if not needed
# If you want to know how to obtain the ID of kv_namespaces, please check here.
# https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/master/doc/en/DEPLOY.md
kv_namespaces = [
  { binding = 'DATABASE', id = '', preview_id = '' }
]


[vars]
# More parameters usage, please see https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/master/doc/en/CONFIG.md
# All variables must be strings, and the values of multiple parameters are separated by commas, such as "a,b,c"
# If the value is a boolean, it is written as "true" or "false"
# If the value is a number, it is written as a string, such as "1", "2", "3"
# If the value is a JSON string, it is written as a string, such as '["a","b","c"]'

# TELEGRAM_AVAILABLE_TOKENS = 'token1,token2'
# CHAT_WHITE_LIST = 'chat_id1,chat_id2'